### PR TITLE
Issue 45 connect login modal to the backend

### LINKED ISSUE #45: Connect login modal to the backend
## Basic Information
BRANCH OFF #12 IF NOT MERGED ALREADY

Create a `useAuth` hook in the `client/src/hooks/auth.ts`. It should contain a method `login()` which when called
- Calls the jwt endpoint with the username and password, this will return a token if it's a valid user
- Store the token in cookies, which will expire after x time (up to your discretion)
- Attach the token to all backend requests with an axios interceptor https://www.thedutchlab.com/en/insights/using-axios-interceptors-for-refreshing-your-api-token . This currently lives in `client/src/lib/api.ts`
- Add an additonal condition: if the backend request fails, try refreshing the token with the corresponding endpoint. Take a look at https://github.com/codersforcauses/csf/blob/b92a97f1656e50b107151af863ee45b166431394/client/src/utils/server.ts#L22 for help (it's in vue but similar concept)

## Other Information
There's no need to use tanstack query for this, (unlike the usePings example). You can just create a vanilla hook

### PR DESCRIPTION
**Pull request by SetroZ**
### **Created useAuth custom hook.**
- returns login, isLoggedIn, logout
- linked useAuth with login modal
- Performs page reloads after logout/ login
- added axios interceptors

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [x] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

# Related issue

- Resolve #45

### CODE REVIEW

**Review by K-Straiton — CHANGES_REQUESTED** [review]
The login and sign in modals have been merged into main now. Please pull from main and merge into your branch, resolve conflicts, and make sure everything is still working.

**Comment by SetroZ** [comment]
Done!

**Comment by Connor2803** [comment]
Works well, but the modal says email, where it only logs you in if you use username.

**Comment by SetroZ** [comment]
I will have to extend simple-JWT serializer to accept email

**Review by K-Straiton — CHANGES_REQUESTED** [review]
Can you please change the front end back to saying email. Since the django default user model uses username as the unique identifier, the backend will also store the user's email in the username field. So for this, the username field will still be used for auth, but the user needs to know to type their email.

 Also, when sign in fails (i.e invalid username or password), that should be shown on the front end, to let user know, either incorrect password or invalid email

**Review by dct0 — APPROVED** [review]

**Review by K-Straiton — APPROVED** [review]

**Pull request merged**
